import type {
  MatchChip,
  MatchMode,
  MatchModeContent,
  MatchModeOption,
  PartnerMatchCardData,
  TripMatchCardData,
} from './types'

export const modeOptions: MatchModeOption[] = [
  { key: 'partner', label: '搭子匹配' },
  { key: 'trip', label: '行程匹配' },
]

const partnerChips: MatchChip[] = [
  { id: 'partner-time', icon: 'calendar', label: '6 月中旬', dropdown: true },
  { id: 'partner-car', icon: 'car', label: '自驾' },
  { id: 'partner-photo', icon: 'camera', label: '摄影' },
  { id: 'partner-mbti', icon: 'user', label: 'ENFP' },
  { id: 'partner-walk', icon: 'walk', label: '轻徒步' },
]

const tripChips: MatchChip[] = [
  { id: 'trip-time', icon: 'calendar', label: '6 月中旬' },
  { id: 'trip-car', icon: 'car', label: '自驾', dropdown: true },
  { id: 'trip-photo', icon: 'camera', label: '摄影', dropdown: true },
  { id: 'trip-people', icon: 'people', label: '2-4人', dropdown: true },
  { id: 'trip-duration', icon: 'clock', label: '6天', dropdown: true },
]

export const matchContent: Record<MatchMode, MatchModeContent> = {
  partner: {
    title: '找旅行搭子',
    placeTitle: '川西（318沿线）',
    placeMeta: '12 人正在找搭子',
    chips: partnerChips,
  },
  trip: {
    title: '找可加入行程',
    placeTitle: '川西（318沿线）',
    placeMeta: '12 人正在找搭子',
    chips: tripChips,
  },
}

export const partnerCards: PartnerMatchCardData[] = [
  {
    id: 'partner-01',
    name: '山间小鹿',
    mbti: 'ENFP',
    avatarTone: 'sunset',
    avatarMark: 'sun',
    online: true,
    personality: '慢熟拍照型 ENFP',
    interests: [
      { icon: 'camera', label: '摄影' },
      { icon: 'walk', label: '徒步' },
      { icon: 'mountain', label: '音乐' },
    ],
    destination: '稻城亚丁 · 四姑娘山',
    departure: '6月12日 - 6月20日',
    summary: '喜欢在路上捕捉光影，也热爱遇见有趣的灵魂。',
    actionLabel: '看看TA',
    profileStatus: '想去川西 · 6 月中旬',
    profileQuote: '想找一个不赶路、愿意一起等日照金山的人',
    matchReasons: [
      { icon: 'pin', label: '目的地一致' },
      { icon: 'calendar', label: '时间相近' },
      { icon: 'heart', label: '兴趣重合 4 项' },
    ],
  },
  {
    id: 'partner-02',
    name: '风的旅人',
    mbti: 'INTJ',
    avatarTone: 'snow',
    avatarMark: 'peak',
    online: true,
    personality: '攻略控 INTJ',
    interests: [
      { icon: 'car', label: '自驾' },
      { icon: 'camera', label: '摄影' },
      { icon: 'mountain', label: '露营' },
    ],
    destination: '新都桥 · 理塘 · 稻城亚丁',
    departure: '6月15日 - 6月24日',
    summary: '真正的风景，永远在下一段路上。',
    actionLabel: '加好友',
    profileStatus: '想去川西 · 6 月中旬',
    profileQuote: '希望找时间观念强、能一起规划路线的搭子',
    matchReasons: [
      { icon: 'pin', label: '路线相近' },
      { icon: 'calendar', label: '日期重叠' },
      { icon: 'heart', label: '自驾偏好一致' },
    ],
  },
  {
    id: 'partner-03',
    name: '云朵收集者',
    mbti: 'INFP',
    avatarTone: 'lake',
    avatarMark: 'cloud',
    online: true,
    personality: '慢节奏 INFP',
    interests: [
      { icon: 'walk', label: '轻徒步' },
      { icon: 'camera', label: '摄影' },
      { icon: 'wallet', label: '咖啡' },
    ],
    destination: '四姑娘山 · 丹巴藏寨',
    departure: '6月18日 - 6月23日',
    summary: '步履轻盈，热爱山野与自由。',
    actionLabel: '看看TA',
    profileStatus: '想去川西 · 6 月中旬',
    profileQuote: '想在雪山和草甸之间慢慢散心',
    matchReasons: [
      { icon: 'pin', label: '目的地相近' },
      { icon: 'calendar', label: '时间匹配' },
      { icon: 'heart', label: '节奏偏好一致' },
    ],
  },
  {
    id: 'partner-04',
    name: '行走的地图',
    mbti: 'INTP',
    avatarTone: 'road',
    avatarMark: 'map',
    online: true,
    personality: '路线探索型 INTP',
    interests: [
      { icon: 'car', label: '自驾' },
      { icon: 'clock', label: '探索' },
      { icon: 'mountain', label: '星空' },
    ],
    destination: '川西大环线（318沿线）',
    departure: '6月10日 - 6月22日',
    summary: '用脚步丈量世界，用好奇心探索未知。',
    actionLabel: '加好友',
    profileStatus: '想去川西 · 6 月中旬',
    profileQuote: '想找能接受临时改线、一起看星空的人',
    matchReasons: [
      { icon: 'pin', label: '路线一致' },
      { icon: 'calendar', label: '时间覆盖' },
      { icon: 'heart', label: '探索偏好一致' },
    ],
  },
]

export const tripCards: TripMatchCardData[] = [
  {
    id: 'trip-01',
    organizerName: '阿曲',
    title: '6月中旬 · 稻城亚丁',
    imageTone: 'valley',
    location: '稻城亚丁',
    dateRange: '6.15 - 6.20',
    transport: '自驾',
    people: '2人 / 6人',
    duration: '6天',
    travelStyle: '自驾 · 2/4人 · 6天',
    summary: '想找会拍照的搭子，一起看雪山！',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-02',
    organizerName: '老周',
    title: '5.25–6.5 · 川西环线',
    imageTone: 'ridge',
    location: '川西环线',
    dateRange: '5.25 - 6.05',
    transport: '自驾',
    people: '3人 / 12人',
    duration: '12天',
    travelStyle: '自驾 · 3/12人 · 12天',
    summary: '老司机带队，找有经验的小伙伴一起出发！',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-03',
    organizerName: 'Mia',
    title: '6月初 · 新都桥',
    imageTone: 'bridge',
    location: '新都桥',
    dateRange: '6.03 - 6.08',
    transport: '自驾',
    people: '2人 / 4人',
    duration: '6天',
    travelStyle: '自驾 · 2/4人 · 6天',
    summary: '主要拍照，慢节奏旅行，期待同频的你~',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-04',
    organizerName: '初七',
    title: '6月 · 四姑娘山',
    imageTone: 'snow',
    location: '四姑娘山',
    dateRange: '6.10 - 6.15',
    transport: '自驾',
    people: '1人 / 5人',
    duration: '6天',
    travelStyle: '自驾 · 1/5人 · 6天',
    summary: '轻装徒步，感受四姑娘山的治愈之美~',
    actionLabel: '申请加入',
  },
]
