import type {
  MatchChip,
  MatchMode,
  MatchModeContent,
  MatchModeOption,
  PartnerMatchCardData,
  TripMatchCardData,
} from './types'
import fengdelvrenAvatar from './assets/partner-fengdelvren.png'
import shanjianxiaoluAvatar from './assets/partner-shanjianxiaolu.png'

export const modeOptions: MatchModeOption[] = [
  { key: 'partner', label: '搭子匹配' },
  { key: 'trip', label: '行程匹配' },
]

const partnerChips: MatchChip[] = [
  { id: 'partner-time', icon: 'calendar', label: '6 月中旬', dropdown: true },
  { id: 'partner-car', icon: 'car', label: '自驾' },
  { id: 'partner-photo', icon: 'camera', label: '摄影' },
  { id: 'partner-persona', icon: 'user', label: '旅行人格' },
  { id: 'partner-walk', icon: 'walk', label: '轻徒步' },
]

const tripChips: MatchChip[] = [
  { id: 'trip-time', icon: 'calendar', label: '6 月中旬' },
  { id: 'trip-car', icon: 'car', label: '自驾', dropdown: true },
  { id: 'trip-photo', icon: 'camera', label: '摄影', dropdown: true },
  { id: 'trip-people', icon: 'people', label: '2-4人', dropdown: true },
  { id: 'trip-duration', icon: 'clock', label: '6天', dropdown: true },
]

export const matchContent: Record<MatchMode, MatchModeContent> = {
  partner: {
    title: '找旅行搭子',
    placeTitle: '西藏',
    placeMeta: '正在寻找同目的地搭子',
    chips: partnerChips,
  },
  trip: {
    title: '找可加入行程',
    placeTitle: '西藏',
    placeMeta: '正在寻找同目的地行程',
    chips: tripChips,
  },
}

export const nearbyDestinationMap: Record<string, string[]> = {
  yunnan: ['yunnan-dali', 'yunnan-lijiang'],
  'yunnan-lijiang': ['yunnan-dali'],
  sichuan: ['sichuan-chuanxi', 'sichuan-chengdu', 'sichuan-daocheng'],
  'sichuan-chengdu': ['sichuan-chuanxi', 'sichuan-daocheng'],
  'sichuan-daocheng': ['sichuan-chuanxi'],
  'sichuan-jiuzhaigou': ['sichuan-chengdu', 'sichuan-chuanxi'],
  'sichuan-luguhu': ['sichuan-daocheng', 'yunnan-dali'],
  xinjiang: ['xinjiang-ili', 'xinjiang-altay'],
  qinghai: ['qinghai-qinghaihu', 'xizang'],
  heilongjiang: ['heilongjiang-harbin'],
  hainan: ['hainan-sanya'],
  zhejiang: ['zhejiang-hangzhou'],
  beijing: ['beijing-gugong'],
  guangdong: ['guangdong-guangzhou', 'hainan-sanya'],
  guangxi: ['guangxi-guilin'],
  jiangsu: ['jiangsu-nanjing', 'zhejiang-hangzhou'],
  'xizang-lhasa': ['xizang'],
  'xizang-linzhi': ['xizang'],
}

export const partnerCards: PartnerMatchCardData[] = [
  {
    id: 'partner-dali-01',
    personaId: 'Romantic-Observer',
    classicMbti: 'ENFP',
    identityStatus: '已实名',
    matchScore: 88,
    travelWay: '慢旅行 · 摄影',
    groupPreference: '2-3 人松弛同行',
    activeTime: '10 分钟前活跃',
    name: '海边的风',
    avatarUrl: shanjianxiaoluAvatar,
    avatarAlt: '海边的风头像',
    online: true,
    personality: '人文浪漫主义 ENFP',
    interests: [
      { icon: 'camera', label: '洱海摄影' },
      { icon: 'walk', label: '古城散步' },
      { icon: 'wallet', label: '咖啡小店' },
    ],
    primaryDestinationId: 'yunnan-dali',
    destinationIds: ['yunnan-dali', 'yunnan'],
    destination: '大理 · 洱海骑行 · 古城晒太阳',
    departure: '6月12日 - 6月16日',
    summary: '想找一个不赶路的人，白天沿洱海骑车，傍晚去古城听一场小现场。',
    profileStatus: '想去大理 · 6 月中旬',
    profileQuote: '比起赶景点，我更想把风、日落和聊天都认真留住。',
    matchReasons: [
      { icon: 'pin', label: '同去大理' },
      { icon: 'calendar', label: '时间相近' },
      { icon: 'heart', label: '慢旅行同频' },
    ],
  },
  {
    id: 'partner-dali-02',
    personaId: 'Zen-Capybara',
    classicMbti: 'INFP',
    identityStatus: '未实名',
    matchScore: 81,
    travelWay: '轻徒步 · 发呆',
    groupPreference: '1-2 人安静同行',
    activeTime: '今天活跃',
    name: '古城晒太阳',
    avatarUrl: fengdelvrenAvatar,
    avatarAlt: '古城晒太阳头像',
    online: true,
    personality: '精神卡皮巴拉 INFP',
    interests: [
      { icon: 'walk', label: '苍山轻徒步' },
      { icon: 'camera', label: '胶片感' },
      { icon: 'wallet', label: '咖啡' },
    ],
    primaryDestinationId: 'yunnan-dali',
    destinationIds: ['yunnan-dali', 'yunnan'],
    destination: '大理古城 · 苍山 · 洱海',
    departure: '6月15日 - 6月18日',
    summary: '不做满行程，想在大理留一点空白，遇到好天气就出门。',
    profileStatus: '想去大理 · 6 月中旬',
    profileQuote: '希望同行的人也能接受临时改变路线。',
    matchReasons: [
      { icon: 'pin', label: '目的地一致' },
      { icon: 'calendar', label: '日期重叠' },
      { icon: 'heart', label: '节奏一致' },
    ],
  },
  {
    id: 'partner-chuanxi-01',
    personaId: 'Budget-Architect',
    classicMbti: 'INTJ',
    identityStatus: '已实名',
    matchScore: 84,
    travelWay: '自驾 · 攻略型',
    groupPreference: '2-4 人小队',
    activeTime: '刚刚活跃',
    name: '风的旅人',
    avatarUrl: fengdelvrenAvatar,
    avatarAlt: '风的旅人头像',
    online: true,
    personality: '精算系旅行家 INTJ',
    interests: [
      { icon: 'car', label: '自驾' },
      { icon: 'camera', label: '雪山摄影' },
      { icon: 'mountain', label: '露营' },
    ],
    primaryDestinationId: 'sichuan-chuanxi',
    destinationIds: ['sichuan-chuanxi', 'sichuan'],
    destination: '川西环线 · 雪山观景 · 高原自驾',
    departure: '6月15日 - 6月22日',
    summary: '路线、预算和天气备选都已整理好，想找能一起执行计划的搭子。',
    profileStatus: '想去川西 · 6 月中旬',
    profileQuote: '希望找时间观念强、能一起规划路线的搭子。',
    matchReasons: [
      { icon: 'pin', label: '路线一致' },
      { icon: 'calendar', label: '日期重叠' },
      { icon: 'heart', label: '自驾偏好一致' },
    ],
  },
  {
    id: 'partner-chuanxi-02',
    personaId: 'Cyber-Raider',
    classicMbti: 'INTP',
    identityStatus: '已实名',
    matchScore: 80,
    travelWay: '探索 · 打卡',
    groupPreference: '2-3 人灵活同行',
    activeTime: '1 小时前活跃',
    name: '行走的地图',
    avatarUrl: shanjianxiaoluAvatar,
    avatarAlt: '行走的地图头像',
    online: true,
    personality: '赛博特种兵 INTP',
    interests: [
      { icon: 'car', label: '自驾' },
      { icon: 'clock', label: '探索' },
      { icon: 'mountain', label: '星空' },
    ],
    primaryDestinationId: 'sichuan-chuanxi',
    destinationIds: ['sichuan-chuanxi', 'sichuan'],
    destination: '川西 · 日照金山 · 星空露营',
    departure: '6月10日 - 6月15日',
    summary: '能早起看日照金山，也能接受临时绕路去看更好的风景。',
    profileStatus: '想去川西 · 6 月中旬',
    profileQuote: '想找能接受临时改线、一起看星空的人。',
    matchReasons: [
      { icon: 'pin', label: '目的地相近' },
      { icon: 'calendar', label: '时间覆盖' },
      { icon: 'heart', label: '探索偏好一致' },
    ],
  },
  {
    id: 'partner-xizang-01',
    personaId: 'Romantic-Observer',
    classicMbti: 'ENFP',
    identityStatus: '已实名',
    matchScore: 85,
    travelWay: '人文 · 慢旅行',
    groupPreference: '2 人安静同行',
    activeTime: '今天活跃',
    name: '日光收集者',
    avatarUrl: shanjianxiaoluAvatar,
    avatarAlt: '日光收集者头像',
    online: true,
    personality: '人文浪漫主义 ENFP',
    interests: [
      { icon: 'camera', label: '寺院光影' },
      { icon: 'walk', label: '慢逛' },
      { icon: 'mountain', label: '高原风景' },
    ],
    primaryDestinationId: 'xizang',
    destinationIds: ['xizang', 'xizang-lhasa'],
    destination: '西藏 · 拉萨 · 寺院光影',
    departure: '6月18日 - 6月24日',
    summary: '想在拉萨慢慢适应海拔，也认真看一整天的日光变化。',
    profileStatus: '想去西藏 · 6 月中旬',
    profileQuote: '希望同行的人尊重节奏，也尊重这片土地。',
    matchReasons: [
      { icon: 'pin', label: '同去西藏' },
      { icon: 'calendar', label: '时间相近' },
      { icon: 'heart', label: '人文兴趣重合' },
    ],
  },
  {
    id: 'partner-chengdu-01',
    personaId: 'Zen-Capybara',
    classicMbti: 'INFP',
    identityStatus: '已实名',
    matchScore: 83,
    travelWay: '城市漫游 · 美食',
    groupPreference: '2 人慢悠悠同行',
    activeTime: '30 分钟前活跃',
    name: '锅边散步',
    avatarUrl: fengdelvrenAvatar,
    avatarAlt: '锅边散步头像',
    online: true,
    personality: '精神卡皮巴拉 INFP',
    interests: [
      { icon: 'wallet', label: '火锅小馆' },
      { icon: 'walk', label: '街巷散步' },
      { icon: 'camera', label: '市井拍照' },
    ],
    primaryDestinationId: 'sichuan-chengdu',
    destinationIds: ['sichuan-chengdu', 'sichuan'],
    destination: '成都 · 茶馆发呆 · 夜宵收尾',
    departure: '6月21日 - 6月24日',
    summary: '更想把时间留给茶馆、火锅和慢慢走的街区，不追赶清单式打卡。',
    profileStatus: '想去成都 · 周末轻松逛',
    profileQuote: '希望能一起边吃边聊，走累了就找家馆子坐下。',
    matchReasons: [
      { icon: 'pin', label: '同去成都' },
      { icon: 'calendar', label: '时间可拼' },
      { icon: 'heart', label: '慢节奏同频' },
    ],
  },
  {
    id: 'partner-daocheng-01',
    personaId: 'Budget-Architect',
    classicMbti: 'INTJ',
    identityStatus: '已实名',
    matchScore: 86,
    travelWay: '高原自驾 · 徒步',
    groupPreference: '2-3 人高配合小队',
    activeTime: '今天活跃',
    name: '海子观测员',
    avatarUrl: shanjianxiaoluAvatar,
    avatarAlt: '海子观测员头像',
    online: true,
    personality: '精算系旅行家 INTJ',
    interests: [
      { icon: 'car', label: '高原自驾' },
      { icon: 'mountain', label: '短线徒步' },
      { icon: 'camera', label: '雪山光线' },
    ],
    primaryDestinationId: 'sichuan-daocheng',
    destinationIds: ['sichuan-daocheng', 'sichuan'],
    destination: '稻城亚丁 · 牛奶海 · 日照金山',
    departure: '6月26日 - 6月30日',
    summary: '已经排好海拔适应和补给节奏，想找有执行力、能互相照应的同行人。',
    profileStatus: '想去稻城亚丁 · 6 月下旬',
    profileQuote: '高原行程留有冗余，但关键节点希望大家都守时。',
    matchReasons: [
      { icon: 'pin', label: '同去亚丁' },
      { icon: 'calendar', label: '窗口重合' },
      { icon: 'heart', label: '徒步预期一致' },
    ],
  },
  {
    id: 'partner-linzhi-01',
    personaId: 'Romantic-Observer',
    classicMbti: 'ENFP',
    identityStatus: '已实名',
    matchScore: 82,
    travelWay: '风景线 · 慢拍',
    groupPreference: '2 人安静搭档',
    activeTime: '2 小时前活跃',
    name: '云海翻译官',
    avatarUrl: shanjianxiaoluAvatar,
    avatarAlt: '云海翻译官头像',
    online: true,
    personality: '人文浪漫主义 ENFP',
    interests: [
      { icon: 'camera', label: '南迦巴瓦' },
      { icon: 'walk', label: '林间散步' },
      { icon: 'mountain', label: '低海拔进藏' },
    ],
    primaryDestinationId: 'xizang-linzhi',
    destinationIds: ['xizang-linzhi', 'xizang'],
    destination: '林芝 · 桃花谷地 · 观景慢游',
    departure: '6月22日 - 6月26日',
    summary: '想在林芝多停几次车，看云、雪山和河谷，不把美景压成打卡任务。',
    profileStatus: '想去林芝 · 6 月下旬',
    profileQuote: '希望同行的人也愿意为一束好光多等十分钟。',
    matchReasons: [
      { icon: 'pin', label: '同去林芝' },
      { icon: 'calendar', label: '时间顺路' },
      { icon: 'heart', label: '拍照审美接近' },
    ],
  },
  {
    id: 'partner-qinghai-01',
    personaId: 'Cyber-Raider',
    classicMbti: 'INTP',
    identityStatus: '已实名',
    matchScore: 84,
    travelWay: '骑行 · 环湖',
    groupPreference: '2-4 人活力同行',
    activeTime: '刚刚活跃',
    name: '高原蹬风者',
    avatarUrl: fengdelvrenAvatar,
    avatarAlt: '高原蹬风者头像',
    online: true,
    personality: '赛博特种兵 INTP',
    interests: [
      { icon: 'clock', label: '早起看湖' },
      { icon: 'mountain', label: '高原挑战' },
      { icon: 'camera', label: '油菜花海' },
    ],
    primaryDestinationId: 'qinghai-qinghaihu',
    destinationIds: ['qinghai-qinghaihu', 'qinghai'],
    destination: '青海湖 · 日出骑行 · 环湖补给',
    departure: '7月3日 - 7月6日',
    summary:
      '计划日出前出发骑一段最美湖岸线，想找体力稳定、愿意早起的人一起冲。',
    profileStatus: '想去青海湖 · 7 月上旬',
    profileQuote: '可以累，但希望累得值得，风景和节奏都别错过。',
    matchReasons: [
      { icon: 'pin', label: '同去青海湖' },
      { icon: 'calendar', label: '日期相邻' },
      { icon: 'heart', label: '户外强度匹配' },
    ],
  },
  {
    id: 'partner-ili-01',
    personaId: 'Romantic-Observer',
    classicMbti: 'ENFP',
    identityStatus: '已实名',
    matchScore: 87,
    travelWay: '花海自驾 · 轻摄影',
    groupPreference: '2-3 人松弛同行',
    activeTime: '15 分钟前活跃',
    name: '紫色风路',
    avatarUrl: shanjianxiaoluAvatar,
    avatarAlt: '紫色风路头像',
    online: true,
    personality: '人文浪漫主义 ENFP',
    interests: [
      { icon: 'camera', label: '薰衣草花海' },
      { icon: 'car', label: '赛里木湖自驾' },
      { icon: 'walk', label: '草原散步' },
    ],
    primaryDestinationId: 'xinjiang-ili',
    destinationIds: ['xinjiang-ili', 'xinjiang'],
    destination: '伊犁 · 花海草原 · 赛里木湖',
    departure: '7月8日 - 7月13日',
    summary: '想把伊犁拍得轻一点、慢一点，给花海和草原都留出停下来的时间。',
    profileStatus: '想去伊犁 · 7 月中旬',
    profileQuote: '如果你也愿意在风里发会儿呆，我们大概会很合拍。',
    matchReasons: [
      { icon: 'pin', label: '同去伊犁' },
      { icon: 'calendar', label: '花期对上' },
      { icon: 'heart', label: '摄影偏好一致' },
    ],
  },
  {
    id: 'partner-harbin-01',
    personaId: 'Budget-Architect',
    classicMbti: 'INTJ',
    identityStatus: '已实名',
    matchScore: 81,
    travelWay: '冬季城市线 · 规划型',
    groupPreference: '2-3 人小分队',
    activeTime: '今天活跃',
    name: '防寒清单控',
    avatarUrl: fengdelvrenAvatar,
    avatarAlt: '防寒清单控头像',
    online: true,
    personality: '精算系旅行家 INTJ',
    interests: [
      { icon: 'wallet', label: '雪季预算' },
      { icon: 'camera', label: '欧式街景' },
      { icon: 'clock', label: '亮灯时刻' },
    ],
    primaryDestinationId: 'heilongjiang-harbin',
    destinationIds: ['heilongjiang-harbin', 'heilongjiang'],
    destination: '哈尔滨 · 中央大街 · 冰雪大世界',
    departure: '12月20日 - 12月24日',
    summary: '已经整理好保暖、票务和夜景时段，想找执行力强一点的冬游搭子。',
    profileStatus: '想去哈尔滨 · 冬季冰雪线',
    profileQuote: '冷不要紧，前提是路线和保暖都提前准备好。',
    matchReasons: [
      { icon: 'pin', label: '同去哈尔滨' },
      { icon: 'calendar', label: '雪季窗口一致' },
      { icon: 'heart', label: '规划偏好接近' },
    ],
  },
  {
    id: 'partner-sanya-01',
    personaId: 'Zen-Capybara',
    classicMbti: 'INFP',
    identityStatus: '未实名',
    matchScore: 80,
    travelWay: '海边度假 · 冲浪体验',
    groupPreference: '1-2 人松弛同行',
    activeTime: '今天活跃',
    name: '海盐入梦',
    avatarUrl: shanjianxiaoluAvatar,
    avatarAlt: '海盐入梦头像',
    online: true,
    personality: '精神卡皮巴拉 INFP',
    interests: [
      { icon: 'walk', label: '海边散步' },
      { icon: 'camera', label: '日落拍照' },
      { icon: 'wallet', label: '椰子咖啡' },
    ],
    primaryDestinationId: 'hainan-sanya',
    destinationIds: ['hainan-sanya', 'hainan'],
    destination: '三亚 · 后海村 · 椰梦长廊',
    departure: '7月12日 - 7月16日',
    summary: '想体验一次不赶海岛项目的度假，上午冲浪，傍晚发呆，晚上散步。',
    profileStatus: '想去三亚 · 7 月海边线',
    profileQuote: '会玩当然很好，但会放空更重要。',
    matchReasons: [
      { icon: 'pin', label: '同去三亚' },
      { icon: 'calendar', label: '日期能拼' },
      { icon: 'heart', label: '松弛度假同频' },
    ],
  },
  {
    id: 'partner-hangzhou-01',
    personaId: 'Romantic-Observer',
    classicMbti: 'ENFP',
    identityStatus: '已实名',
    matchScore: 82,
    travelWay: 'citywalk · 茶园',
    groupPreference: '2 人轻松互拍',
    activeTime: '40 分钟前活跃',
    name: '苏堤晨雾',
    avatarUrl: fengdelvrenAvatar,
    avatarAlt: '苏堤晨雾头像',
    online: true,
    personality: '人文浪漫主义 ENFP',
    interests: [
      { icon: 'camera', label: '西湖晨光' },
      { icon: 'walk', label: '南宋御街' },
      { icon: 'wallet', label: '龙井喝茶' },
    ],
    primaryDestinationId: 'zhejiang-hangzhou',
    destinationIds: ['zhejiang-hangzhou', 'zhejiang'],
    destination: '杭州 · 西湖晨跑 · 龙井慢行',
    departure: '6月28日 - 6月30日',
    summary: '想在杭州走一条不着急的线，早起看湖，白天喝茶，傍晚收一轮日落。',
    profileStatus: '想去杭州 · 周末 citywalk',
    profileQuote: '如果你也喜欢边走边拍、边聊边逛，会很合适。',
    matchReasons: [
      { icon: 'pin', label: '同去杭州' },
      { icon: 'calendar', label: '周末同档' },
      { icon: 'heart', label: '城市漫游同频' },
    ],
  },
  {
    id: 'partner-beijing-01',
    personaId: 'Budget-Architect',
    classicMbti: 'INTJ',
    identityStatus: '已实名',
    matchScore: 79,
    travelWay: '博物馆线 · 历史向',
    groupPreference: '2 人深度同行',
    activeTime: '昨天活跃',
    name: '宫墙研究员',
    avatarUrl: shanjianxiaoluAvatar,
    avatarAlt: '宫墙研究员头像',
    online: false,
    personality: '精算系旅行家 INTJ',
    interests: [
      { icon: 'walk', label: '宫廷中轴线' },
      { icon: 'camera', label: '红墙对称' },
      { icon: 'clock', label: '预约错峰' },
    ],
    primaryDestinationId: 'beijing-gugong',
    destinationIds: ['beijing-gugong', 'beijing'],
    destination: '北京 · 故宫博物院 · 胡同延伸线',
    departure: '7月5日 - 7月7日',
    summary: '想认真看故宫建筑和文物，不只打卡拍照，节奏会偏深度体验。',
    profileStatus: '想去北京 · 人文博物馆线',
    profileQuote: '慢一点没关系，但希望每一段都看得有内容。',
    matchReasons: [
      { icon: 'pin', label: '同去北京' },
      { icon: 'calendar', label: '时间重合' },
      { icon: 'heart', label: '人文兴趣相近' },
    ],
  },
]

export const tripCards: TripMatchCardData[] = [
  {
    id: 'trip-dali-01',
    primaryDestinationId: 'yunnan-dali',
    destinationIds: ['yunnan-dali', 'yunnan'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['洱海骑行', '古城夜游', '苍山半日'],
    organizerName: '阿蓝',
    title: '6月中旬 · 大理慢游',
    imageTone: 'bridge',
    location: '大理 · 洱海',
    dateRange: '6.12 - 6.16',
    transport: '骑行 / 打车',
    people: '2人 / 4人',
    duration: '5天',
    travelStyle: '慢旅行 · 2/4人 · 5天',
    summary: '白天沿洱海骑行，晚上回古城听音乐，行程留足发呆时间。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-dali-02',
    primaryDestinationId: 'yunnan-dali',
    destinationIds: ['yunnan-dali', 'yunnan'],
    status: 'OPEN',
    identityStatus: '发起人未实名',
    planHighlights: ['苍山轻徒步', '咖啡小店', '日落机位'],
    organizerName: '小满',
    title: '6月下旬 · 大理古城发呆计划',
    imageTone: 'valley',
    location: '大理古城',
    dateRange: '6.20 - 6.23',
    transport: '步行 / 打车',
    people: '1人 / 3人',
    duration: '4天',
    travelStyle: '轻徒步 · 1/3人 · 4天',
    summary: '适合不赶路的人，重点是苍山、咖啡和一场不预设结果的日落。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-chuanxi-01',
    primaryDestinationId: 'sichuan-chuanxi',
    destinationIds: ['sichuan-chuanxi', 'sichuan'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['川西环线', '老司机带队', '露营可选'],
    organizerName: '老周',
    title: '5.25-6.5 · 川西环线',
    imageTone: 'ridge',
    location: '川西环线',
    dateRange: '5.25 - 6.05',
    transport: '自驾',
    people: '3人 / 8人',
    duration: '12天',
    travelStyle: '自驾 · 3/8人 · 12天',
    summary: '老司机带队，找有经验的小伙伴一起出发。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-chuanxi-02',
    primaryDestinationId: 'sichuan-chuanxi',
    destinationIds: ['sichuan-chuanxi', 'sichuan'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['雪山观景', '控制强度', '安全结伴'],
    organizerName: '初七',
    title: '6月 · 川西雪山小队',
    imageTone: 'snow',
    location: '川西 · 雪山线',
    dateRange: '6.10 - 6.15',
    transport: '自驾',
    people: '1人 / 5人',
    duration: '6天',
    travelStyle: '自驾 · 1/5人 · 6天',
    summary: '轻装看雪山，行程强度可控，优先安全结伴。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-xizang-01',
    primaryDestinationId: 'xizang',
    destinationIds: ['xizang', 'xizang-lhasa'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['拉萨适应', '寺院光影', '慢节奏'],
    organizerName: '日央',
    title: '6月中旬 · 西藏日光计划',
    imageTone: 'snow',
    location: '西藏 · 拉萨',
    dateRange: '6.18 - 6.24',
    transport: '火车 / 市内打车',
    people: '2人 / 4人',
    duration: '7天',
    travelStyle: '人文 · 2/4人 · 7天',
    summary: '先适应海拔，再慢慢看寺院、街巷和高原上的日光。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-chengdu-01',
    primaryDestinationId: 'sichuan-chengdu',
    destinationIds: ['sichuan-chengdu', 'sichuan'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['茶馆发呆', '火锅夜宵', '熊猫基地错峰'],
    organizerName: '丸子',
    title: '周末成都慢悠悠小队',
    imageTone: 'bridge',
    location: '成都',
    dateRange: '6.21 - 6.23',
    transport: '地铁 / 打车',
    people: '2人 / 4人',
    duration: '3天',
    travelStyle: '城市漫游 · 2/4人 · 3天',
    summary: '主打吃、逛、坐，留足临时改线空间，适合第一次来成都的人加入。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-daocheng-01',
    primaryDestinationId: 'sichuan-daocheng',
    destinationIds: ['sichuan-daocheng', 'sichuan'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['亚丁短徒步', '牛奶海天气窗', '高原适应'],
    organizerName: '北斗',
    title: '6月末 · 稻城亚丁适应式行程',
    imageTone: 'ridge',
    location: '稻城亚丁',
    dateRange: '6.26 - 6.30',
    transport: '包车 / 自驾',
    people: '2人 / 5人',
    duration: '5天',
    travelStyle: '高原徒步 · 2/5人 · 5天',
    summary:
      '路线预留天气和身体状态弹性，更适合第一次去亚丁、但又不想太赶的人。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-linzhi-01',
    primaryDestinationId: 'xizang-linzhi',
    destinationIds: ['xizang-linzhi', 'xizang'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['林芝河谷', '观景平台停靠', '低强度进藏'],
    organizerName: '阿措',
    title: '6月下旬 · 林芝轻松看云线',
    imageTone: 'valley',
    location: '林芝',
    dateRange: '6.22 - 6.26',
    transport: '包车',
    people: '1人 / 4人',
    duration: '5天',
    travelStyle: '风景慢游 · 1/4人 · 5天',
    summary: '节奏比拉萨线更轻，适合想拍风景、慢慢适应海拔的人。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-qinghai-01',
    primaryDestinationId: 'qinghai-qinghaihu',
    destinationIds: ['qinghai-qinghaihu', 'qinghai'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['青海湖日出', '油菜花带', '轻骑行体验'],
    organizerName: '阿树',
    title: '7月 · 青海湖追风计划',
    imageTone: 'snow',
    location: '青海湖',
    dateRange: '7.03 - 7.06',
    transport: '包车 / 骑行',
    people: '2人 / 5人',
    duration: '4天',
    travelStyle: '户外骑行 · 2/5人 · 4天',
    summary: '以看湖和轻度户外为主，每天只留一个核心目标，避免高原赶路。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-ili-01',
    primaryDestinationId: 'xinjiang-ili',
    destinationIds: ['xinjiang-ili', 'xinjiang'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['赛里木湖', '那拉提', '薰衣草花期'],
    organizerName: '夏河',
    title: '7月中旬 · 伊犁花海草原线',
    imageTone: 'valley',
    location: '伊犁',
    dateRange: '7.08 - 7.13',
    transport: '自驾',
    people: '2人 / 4人',
    duration: '6天',
    travelStyle: '花海自驾 · 2/4人 · 6天',
    summary:
      '行程不拉满，把最好的时间给赛里木湖和那拉提，适合喜欢拍照的人加入。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-harbin-01',
    primaryDestinationId: 'heilongjiang-harbin',
    destinationIds: ['heilongjiang-harbin', 'heilongjiang'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['中央大街', '冰雪大世界', '索菲亚教堂夜拍'],
    organizerName: '小北',
    title: '冬季哈尔滨亮灯线',
    imageTone: 'snow',
    location: '哈尔滨',
    dateRange: '12.20 - 12.24',
    transport: '步行 / 打车',
    people: '2人 / 4人',
    duration: '5天',
    travelStyle: '冬日城市线 · 2/4人 · 5天',
    summary: '围绕亮灯时间和保暖节奏安排，适合第一次看东北冰雪的人一起去。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-sanya-01',
    primaryDestinationId: 'hainan-sanya',
    destinationIds: ['hainan-sanya', 'hainan'],
    status: 'OPEN',
    identityStatus: '发起人未实名',
    planHighlights: ['后海冲浪', '椰梦长廊', '免税店可选'],
    organizerName: '沐夏',
    title: '三亚海风松弛局',
    imageTone: 'bridge',
    location: '三亚',
    dateRange: '7.12 - 7.16',
    transport: '打车 / 拼车',
    people: '1人 / 4人',
    duration: '5天',
    travelStyle: '海边度假 · 1/4人 · 5天',
    summary: '每天只安排一件正事，其他时间交给海风、咖啡和日落。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-hangzhou-01',
    primaryDestinationId: 'zhejiang-hangzhou',
    destinationIds: ['zhejiang-hangzhou', 'zhejiang'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['西湖清晨', '龙井村', '南宋御街 citywalk'],
    organizerName: '小舟',
    title: '杭州两日松弛 citywalk',
    imageTone: 'bridge',
    location: '杭州',
    dateRange: '6.28 - 6.29',
    transport: '步行 / 公交',
    people: '2人 / 4人',
    duration: '2天',
    travelStyle: '城市慢游 · 2/4人 · 2天',
    summary: '路线轻松，兼顾西湖、茶园和老街，适合周末临时加入。',
    actionLabel: '申请加入',
  },
  {
    id: 'trip-beijing-01',
    primaryDestinationId: 'beijing-gugong',
    destinationIds: ['beijing-gugong', 'beijing'],
    status: 'OPEN',
    identityStatus: '发起人已实名',
    planHighlights: ['故宫讲解', '景山俯瞰', '胡同晚餐'],
    organizerName: '十三',
    title: '北京红墙胡同深度线',
    imageTone: 'ridge',
    location: '北京',
    dateRange: '7.05 - 7.07',
    transport: '地铁 / 步行',
    people: '2人 / 4人',
    duration: '3天',
    travelStyle: '人文博物馆线 · 2/4人 · 3天',
    summary: '主打故宫和老城慢逛，适合想认真看历史空间而不是赶热门榜单的人。',
    actionLabel: '申请加入',
  },
]
